server:
  port: 8080

# 数据库
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-mybatis?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:com/ws/study/springboot/mybatis/*/mapper/*.xml